---

- hosts: all
  tasks:

  - name: update repository 
    apt: 
      update_cache: yes

  - name: install httpd
    apt:           # module "apt"
      name: apache2  # install apache2 
      state: absent

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: absent


