- name: install httpd and libapache2-mod-php 
  #apt:           # module "apt" only for Ubuntu like
  #dnf:           # module "dnf" only for CentOS like 
  package:        # module "packege" for all linux-s  
    name:     
      - "{{ apache_package }}"             # install apache2
      - "{{ php_package }}"  # install libapache2-mod-php 
    state: latest
    update_cache: yes

- name: crate mojeico user
  tags: user,centos
  user:
    name: mojeico
    groups: root
  notify: create_user_mojeico # if user was created run create_user_mojeico in handler folder

- name: add ssh key for mojeico user
  tags: centos,ssh
  authorized_key: 
    user: mojeico
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCR5uEudXLsEv8KvZbn/42rBOCCxaYM47wsU1Puldi0T6QLGw0nt9IYybEuVvHPBY5ft2PhZrB4fmqR1Ci7F7Etd2dfXdfSoX5MEL4TMWDMybhyGNzuKB//+aIqEuyKr90qfCl0Qr64DgQtQXOckm5IAXhhiHEzfe2ZJvMrWrz87QpbUenM7W6OeDP6UYvjsdM3DFSLOTFs+PJcJ7xd5rJovDfg87jwM9EpIg+Ozswwe0uNutuKsQcrUEnqfIZzNyFpENGGWedjRBIldraXjIqred2X2dZKQGcUKjwtiaM9FwTifyapFC9jUR3F9zy//pVsuO2A/vK6zHfREN66xkFYLxURH+SMj9BpbYiZYfzkZzYovAU4ysyXo7/p19QWKx5e8BW4KTKhgQy0ruj1amdWhibg7LUZgxIOMZXFlxVDALiaFbmCygua047hjoXCEZHtdP4rHbF3HqW3+rG5is1rTvElEzfI6qXGYZLiplb8IKQ5HvtThTu3Dp/UKK8Fx0= gleb.mojeico@X706HG6HJ4"
  

- name: add soudoers file for mojeico user
  tags: user,sudoers
  copy:
    src: sudoers_mojeico
    dest: /etc/sudoers.d/mojeico
    owner: root
    group: root
    mode: 0440
